1. 由于node服务是非阻塞单线程的,一旦程序中报错，抛出异常就会整个停掉

#### 原因
1. throw new error 没有捕获
2. promise错误回调没有接受

### 处理方式 给整个进程process对象监听

#### express 异常处理

#### domain